/**
* OOPSBannerApp UC1 - 0OPS Banner Display Application
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorative
* text effect.
*
* <p>The banner is generated by printing predefined string patterns line by line,
* where each line contributes to forming the letters 0, O, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
* </p>
*
* @author Somanshu
* @version 2.0
*/


public class oopsbannerapp{
    public static void main(String[]args){
        String[] lines = {
            String.join(" ", " *** ", " *** ", " **** ", " **** "),
            String.join(" ", "*   *", "*   *", "*   *", "*     "),
            String.join(" ", "*   *", "*   *", "*   *", "*     "),
            String.join(" ", "*   *", "*   *", " **** ", " ***  "),
            String.join(" ", "*   *", "*   *", "*     ", "    * "),
            String.join(" ", "*   *", "*   *", "*     ", "    * "),
            String.join(" ", " *** ", " *** ", "*     ", " **** ")
        };

        // Enhanced for-loop to print each banner line
        for (String line : lines) {
            System.out.println(line);}

    }
}