/**
* OOPSBannerApp UC1 - 0OPS Banner Display Application
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorative
* text effect.
*
* <p>The banner is generated by printing predefined string patterns line by line,
* where each line contributes to forming the letters 0, O, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
* </p>
*
* @author Somanshu
* @version 2.0
*/


import java.util.HashMap;
public class oopsbannerapp {

    public static HashMap<Character, String[]> createCharacterMap() {

        HashMap<Character, String[]> charMap = new HashMap<>();

        // Letter O
        charMap.put('O', new String[]{
                " *** ",
                "*   *",
                "*   *",
                "*   *",
                "*   *",
                "*   *",
                " *** "
        });

        // Letter P
        charMap.put('P', new String[]{
                "**** ",
                "*   *",
                "*   *",
                "**** ",
                "*    ",
                "*    ",
                "*    "
        });

        // Letter S
        charMap.put('S', new String[]{
                " ****",
                "*    ",
                "*    ",
                " *** ",
                "    *",
                "    *",
                "**** "
        });

        // Space character
        charMap.put(' ', new String[]{
                "     ",
                "     ",
                "     ",
                "     ",
                "     ",
                "     ",
                "     "
        });

        return charMap;
    }

    public static void displayBanner(String message,
                                     HashMap<Character, String[]> charMap) {

        int patternHeight = charMap.get('O').length; // assuming uniform height

        for (int line = 0; line < patternHeight; line++) {

            StringBuilder sb = new StringBuilder();

            for (char ch : message.toCharArray()) {

                String[] pattern = charMap.getOrDefault(ch, charMap.get(' '));
                sb.append(pattern[line]).append(" ");
            }

            System.out.println(sb.toString());
        }
    }

    /**
     * Main method – Entry point
     */
    public static void main(String[] args) {

        HashMap<Character, String[]> charMap = createCharacterMap();

        String message = "OOPS";

        displayBanner(message, charMap);
    }
}